# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_device_id', models.CharField(max_length=255)),
                ('to_device_id', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.CharField(max_length=255)),
                ('subscribed_to', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='devicesubscription',
            unique_together=set([('subscriber', 'subscribed_to')]),
        ),
    ]
